# Generated by Django 3.2.9 on 2021-12-03 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('rountingnumber', models.CharField(default='', max_length=200)),
                ('username', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocalBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('username', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('rountingnumber', models.CharField(default='', max_length=9)),
                ('Accountnumber', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('accountnumber', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.FloatField(default=0)),
                ('Balance', models.CharField(max_length=200)),
                ('BankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankDetails.localbank')),
                ('UserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankDetails.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accountnumber', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('completed', 'completed')], max_length=200, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('ForiegnBankrountingnumber', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='bankdetails_transaction_related', to='BankDetails.foreignbank')),
                ('FromBank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankdetails_transaction_related', to='BankDetails.localbank')),
                ('Name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BankDetails.userprofile')),
                ('toBank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankDetails.foreignbank')),
            ],
        ),
    ]
