# Generated by Django 3.2.9 on 2021-12-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('IFSC', models.CharField(default='', max_length=200)),
                ('BankCode', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transanction_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accountnumber', models.CharField(default='', max_length=200)),
                ('Type', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], max_length=200, unique=True)),
                ('FromBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transanction_model_requests_created', to='BankDetails.bank')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.CharField(max_length=200)),
                ('AccountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountNumber', to='BankDetails.transanction_model')),
                ('BankId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankDetails.bank')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
            ],
        ),
    ]
