# Generated by Django 3.2.9 on 2021-12-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transanction_model',
            name='FromBank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transanction_model_requests_created', to='BankDetails.bank'),
        ),
    ]
