# Generated by Django 3.2.9 on 2021-12-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignbank',
            name='rountingnumber',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Accountnumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accountnumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
