# Generated by Django 3.2.9 on 2021-12-01 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0002_auto_20211202_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('accountnumber', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='transanction',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankDetails.userprofile'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankDetails.userprofile'),
        ),
    ]
