# Generated by Django 3.2.9 on 2021-12-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0003_auto_20211202_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignbank',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
