# Generated by Django 3.2.9 on 2021-12-01 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0004_foreignbank_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='AccountNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountNumber', to='BankDetails.userprofile'),
        ),
    ]
