# Generated by Django 3.2.9 on 2021-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0007_transanction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transanction',
            name='amount',
            field=models.FloatField(blank=True),
        ),
    ]
