# Generated by Django 3.2.9 on 2021-12-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0007_transaction_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
    ]
