# Generated by Django 3.2.9 on 2021-12-08 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0008_remove_transaction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completeddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
