# Generated by Django 3.2.9 on 2021-12-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0009_alter_transanction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transanction',
            name='amount',
        ),
    ]
