# Generated by Django 3.2.9 on 2021-12-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0010_auto_20211209_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='completeddate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='confirmdate',
            field=models.DateField(default=''),
        ),
    ]
