# Generated by Django 4.0 on 2021-12-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0011_auto_20211209_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ForiegnBankrountingnumber',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='BankDetails.foreignbank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='FromBank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='BankDetails.localbank'),
        ),
    ]
