# Generated by Django 3.2.9 on 2021-12-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0012_auto_20211209_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bankId',
            field=models.ForeignKey(default='', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='BankDetails.localbank'),
        ),
    ]
