# Generated by Django 4.0 on 2021-12-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0012_alter_transaction_foriegnbankrountingnumber_and_more'),
        ('BankDetails', '0013_userprofile_bankid'),
    ]

    operations = [
    ]
