# Generated by Django 3.2.9 on 2021-12-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0012_alter_transaction_foriegnbankrountingnumber_and_more'),
        ('BankDetails', '0013_userprofile_bankid'),
    ]

    operations = [
    ]
