# Generated by Django 3.2.9 on 2021-12-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0014_alter_transanction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accountnumber', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('completed', 'completed')], max_length=200, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('FromBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankdetails_transaction_related', to='BankDetails.localbank')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankDetails.userprofile')),
                ('toBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankDetails.foreignbank')),
            ],
        ),
        migrations.DeleteModel(
            name='Transanction',
        ),
    ]
