# Generated by Django 3.2.9 on 2021-12-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0015_auto_20211209_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localbank',
            name='Accountnumber',
        ),
    ]
