# Generated by Django 4.0 on 2021-12-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0014_merge_20211208_2238'),
        ('BankDetails', '0015_auto_20211209_0558'),
    ]

    operations = [
    ]
