# Generated by Django 3.2.9 on 2021-12-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankDetails', '0016_merge_20211209_0127'),
        ('BankDetails', '0016_remove_localbank_accountnumber'),
    ]

    operations = [
    ]
