# Generated by Django 3.2.9 on 2021-12-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
